# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christian Genco
email: christian@gen.co
description: "Blog and projects of an internet micropreneur, software engineer, mustachian, and stage actor."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://christian.gen.co" # the base hostname & protocol for your site
twitter_username: cgenco
github_username:  christiangenco

# Build settings
markdown: kramdown

permalink: :title

# page defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # can be pages, posts, or drafts
    values:
      layout: "post"
      author: Christian Genco
